[package]
name = "phoenix-native"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
phoenix-analytics = { path = "../phoenix-analytics" }
phoenix-graph = { path = "../phoenix-graph" }
phoenix-runtime = { path = "../phoenix-runtime" }
phoenix-store-cozo = { path = "../phoenix-store-cozo" }
phoenix-types = { path = "../phoenix-types" }
serde = { workspace = true }
thiserror = { workspace = true }
