[package]
name = "phoenix-hyperbolic"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
memmap2 = "0.9"
rand = "0.8"
serde = { workspace = true, features = ["derive"] }
bincode = { workspace = true }
thiserror = { workspace = true }
bytemuck = "1.14"
