[package]
name = "phoenix-triverse"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
phoenix-graptor = { path = "../phoenix-graptor" }
phoenix-invarant = { path = "../phoenix-invarant" }
phoenix-lex = { path = "../phoenix-lex" }
phoenix-store-cozo = { path = "../phoenix-store-cozo" }
phoenix-store-native = { path = "../phoenix-store-native" }
phoenix-types = { path = "../phoenix-types" }
rustc-hash.workspace = true
scirs2-graph = "0.4.1"
serde.workspace = true
serde_json.workspace = true
