[package]
name = "phoenix-perf"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
overgraph.workspace = true
phoenix-graph-kernel = { path = "../phoenix-graph-kernel" }
phoenix-ingest-overgraph = { path = "../phoenix-ingest-overgraph" }
phoenix-runtime = { path = "../phoenix-runtime" }
phoenix-store-native-core = { path = "../phoenix-store-native-core" }
phoenix-store-overgraph = { path = "../phoenix-store-overgraph" }
phoenix-types = { path = "../phoenix-types" }
serde.workspace = true
serde_json.workspace = true
